services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env      
    command: ["./main"]

  test:
    build:
      context: .
    command: ["go", "test", "-v", "./..."]
    volumes:
      - .:/app    
    environment:
      OPENWEATHERMAP_API_KEY: "mock-api-key"
      OPENAI_API_KEY: "mock-api-key"